DROP TABLE IF EXISTS TB_USER_MASTER;
create table IF NOT EXISTS TB_CUST_MASTER(
ID integer not null AUTO_INCREMENT,
USER_NAME varchar (200), 
FIRST_NAME varchar(100),
LAST_NAME varchar(100), 
USER_EMAIL varchar(255),
DOJ TIMESTAMP,
CREATED_BY varchar(255), 
CREATED_DT TIMESTAMP,
MODIFIED_BY varchar(255), 
MODIFIED_DT TIMESTAMP,
PRIMARY KEY (ID)

);
DROP TABLE IF EXISTS TB_TRAVELLER;
create table IF NOT EXISTS  TB_TRAVELLER(
TRAVELLER_ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(200) NOT NULL,
CREATED_BY varchar(255),
CREATED_DT TIMESTAMP,
MODIFIED_BY varchar(255),
MODIFIED_DT TIMESTAMP,
NATIONALITY VARCHAR(100) NOT NULL
);
DROP TABLE IF EXISTS TB_TICKETS;
CREATE TABLE TB_TICKETS(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  DESTINATION VARCHAR(100) NOT NULL,
  TICKET_PRICE NUMERIC(8,2) NOT NULL,
  CREATED_BY varchar(255),
  CREATED_DT TIMESTAMP,
  MODIFIED_BY varchar(255),
  MODIFIED_DT TIMESTAMP,
  TRAVELLER_ID INT,
  foreign key (TRAVELLER_ID) references TB_TRAVELLER(TRAVELLER_ID)
);
DROP TABLE IF EXISTS TB_CORPORATE_CUSTOMER;
CREATE TABLE  TB_CORPORATE_CUSTOMER(
CORPORATE_ID int not null,
CORPORATE_NAME varchar(255) not null,
ADDRESS varchar(255),
TOTAL_VALUE int,
CONSTRAINT CompKey_ID_NAME PRIMARY KEY (CORPORATE_ID, CORPORATE_NAME)


);
